### PR TITLE
Created the controller to Get all shops

### PR DESCRIPTION
**Pull request by Oludayo20**
you can check this one that was used for the previous cohort

[# Fixes Issue/Linear Ticket](https://linear.app/zuri-project-backend/issue/COM-30/shop-api)
#Shops Issue

> This could be an existing issue or a linear ticket
>
> - Github Issue Example: My PR Closes Shops Issue
> - Linear Ticket Example: Fixes ID-COM-30

# Changes proposed

I created an endpoint and route that encapsulate the logic for retrieving a list of shops from a database using Prisma. This function handles both success and error scenarios, sending appropriate responses back to the client via the provided Response object.

# Check List (Check all the applicable boxes)

:rotating_light:Please review the [style guide for contributing](add link here) and [guidelines for contributing](add link here) to this repository.

- [v] My code follows the code style of this project.
- [v] This PR does not contain plagiarized content.
- [v] The title and description of the PR is clear and explains the approach.
- [v] I am making a pull request against the **main branch** (left side).
- [v] My commit messages styles matches our requested structure.
- [v] My code additions will fail neither code linting checks nor unit test.
- [v] I am only making changes to files I was requested to.

image

### CODE REVIEW

**Comment by edahmitchel** [comment]
Check the changes you made to docs

**Comment by Oludayo20** [comment]
I don't understand you bro... Even if it's going to take you hour's to merge or give feedback, Please give a detailed one so i will know what to do!!

**Comment by edahmitchel** [comment]
- There's no documentation for the  changes you made -i can't find it in the swagger docs  
- You made changes to the docs that were irrelevant to the endpoint you  worked on
-  You also have to pull and resolve conflicts

**Comment by Oludayo20** [comment]
It's there boss. 
image

that's prove.
U merging everytime that's why i'm constally having conflit

**Review by edahmitchel — APPROVED** [review]

**Pull request merged**
