### PR TITLE
Feat get all categories

### PR DESCRIPTION
**Pull request by thegodhope**
# Fixes Issue/Linear Ticket
[https://linear.app/zuri-project-backend/issue/COM-20/api-to-get-all-categories](url)

•I created an endpoint that get all product categories and subcategories.

•This endpoint does not require authentication

•You can test the endpoint using Postman.

# Changes proposed

> I wrote the controller code and initialize the route
>Wrote the documentation in the swagger.json file.

# Check List (Check all the applicable boxes)

:rotating_light:Please review the [style guide for contributing](add link here) and [guidelines for contributing](add link here) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **main branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos
8A9DAEAB-ECD1-4B4C-87EA-EE35434CD4E2

### CODE REVIEW

**Review by Benrobo — CHANGES_REQUESTED** [review]
you dont need to define a `try {}....catch{}` block statement within getAllCategories

**Comment by Benrobo** [comment]
resolve your conflict as well

**Comment by thegodhope** [comment]
conflict fixed

**Comment by thegodhope** [comment]
I removed the trycatch. A mistake 🤦‍♀️

**Pull request merged**
