### PR TITLE
Implemented the Update Product endpoint and docs

### PR DESCRIPTION
**Pull request by ExtranoDev**
you can check this one that was used for the previous cohort

# Fixes Issue/Linear Ticket

> This could be an existing issue or a linear ticket
>
> - Github Issue Example: My PR Closes #{ISSUE}
> - Linear Ticket Example: [Fixes ID-#{ISSUE}](https://linear.app/zuri-project-backend/issue/COM-18/api-to-update-products)

# Changes proposed

> Talk about the things you did eg. files changes, dependencies installed e.t.c

# Check List (Check all the applicable boxes)

:rotating_light:Please review the [style guide for contributing](add link here) and [guidelines for contributing](add link here) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [ ] I am making a pull request against the **main branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

Updating Product with image:
Screenshot 2023-10-13 114322
Updating Product without Image:
Screenshot 2023-10-13 114356

### CODE REVIEW

**Comment by Benrobo** [comment]
resolve conflict

**Comment by ExtranoDev** [comment]
Conflicts has been resolved

**Comment by Benrobo** [comment]
resolve conflict

**Comment by ExtranoDev** [comment]
Conflict resolved

**Comment by Benrobo** [comment]
@ExtranoDev can you look at how the addProduct is been done and see what you can refactor from it to get yours done.. the addProduct now prompt the user to add other fields within the formData not just image and json.. json field isn't among any longer as all required fields can be passed on as a new field within the form data.

**Comment by ExtranoDev** [comment]
I will have to change the way I accept product information then, I've done that and I want to call your attention to getting  userId in the add product currently the testID is used because the req.user.userId is not available I believe frontend will handle that but I should be fine now

Boss in case of conflict when you want to merge I'm very sure it will be from doc it's something you should be able to resolve for me instead of waiting for me to start create commit and push cos there's no much time again

**Comment by ExtranoDev** [comment]
Conflict resolved

**Pull request closed without merging**
