### PR TITLE
Improved error handling and HTTP status codes in ProductController's …

### PR DESCRIPTION
**Pull request by EzeibekweEmma**
you can check this one that was used for the previous cohort

# Fixes Issue/Linear Ticket

> This could be an existing issue or a linear ticket
>
> - Linear Ticket: Fixes ID-#{COM-21}

# Changes proposed

> Improved error handling and HTTP status codes in ProductController's getAllProducts method
> This commit enhances the getAllProducts method in the ProductController by improving error handling, using appropriate > > HTTP status codes, and adding comments for clarity.

# Check List (Check all the applicable boxes)

:rotating_light:Please review the [style guide for contributing](add link here) and [guidelines for contributing](add link here) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **main branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

### CODE REVIEW

**Review by Benrobo — CHANGES_REQUESTED** [review]
there's no point doing this:

```js
 if (!userId) {
        return res.status(400).json({
          status: 'error',
          message: 'User ID is missing in the request.',
        });
      }
```

also why use 

```
 res.status(404).json({
          status: 'error',
          message: 'No products found for this user.',
        });
```

when you have `this.error` and `this.success`?

Dont use try....catch block within the controller method, it already been handled

**Review by chriss1525 — DISMISSED** [review]

**Comment by EzeibekweEmma** [comment]
fix it

**Review by Benrobo — CHANGES_REQUESTED** [review]
Screenshot 2023-10-12 at 12 49 57 PM

those are not necessary.. if the product dont exists, why send a success response... 

secondly, you dont need to check if product exists or not, if it doesn't exists an empty array would be returned..

**Comment by Benrobo** [comment]
pls fix your logic error, you've not done that

**Comment by Afomachinenye** [comment]
This is not the logic I have on my pull request. Did someone modify
the logic I wrote?

Below is what I have: async getAllProducts(req: Request, res: Response) {
    const products = await prisma.product.findMany();
    this.success(res, "All Products shown", "Product has been outlisted",
200, products);
  }

  async deleteProduct(req: Request, res: Response) {
    const productId = req.params.productId;

      const deletedProduct = await prisma.product.delete({
        where: {
          id: productId,
        },
      });
      if (deletedProduct) {
        this.success(res, 'Product Deleted', 'Product has been deleted
successfully', 200, deletedProduct);
      }
    }
}

**Pull request closed without merging**
