### PR TITLE
Feat: search order by productName& pagination

### PR DESCRIPTION
**Pull request by DimTony**
# Implements Linear Ticket

> Implements Linear Ticket#[[Ticket](https://linear.app/zuri-project-backend/issue/COM-24/api-to-search-other-by-product-name)]

# Changes proposed

This PR introduces two significant enhancements to our application's order search functionality: case-insensitive search and pagination.

### Case-Insensitive Search
The case-insensitive search functionality handles users input names with variations in letter casing. I've implemented case-insensitive searching using the ILIKE syntax, ensuring that users can find what they need, regardless of letter casing.

### Pagination
I've added pagination support to the order search. This will improve the user experience by returning results in manageable chunks, helping to avoid long response times when a large number of orders match the search criteria. Users can now specify the page they want to view and set the page size according to their preference.

# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **main branch** (left side).
- [x] My commit messages styles match our requested structure.
- [x] My code additions will fail neither code linting checks nor unit tests.
- [x] I am only making changes to files I was requested to.

# Usage
Testing steps:
Step 0: Get a valid authentication token (else you run into an unauthorized error)
Step1: Create your .env file providing your DATABASE_URL variable
Step 2: Populate your database
Step 3: Start the server and launch your test client (e.g. postman)
Step 4: Send a GET request to /api/orders/search/:name where "name" is a partial or full name of the product you intend to search

# Screenshots/ Videos
The image below shows my request returning a product "longchair" by searching "chair" in the endpoint.

The image below shows the rest of the response.

The image below shows the response for an unauthorized user coming from the authentication service.

### CODE REVIEW

**Review by chriss1525 — CHANGES_REQUESTED** [review]
Fix your merge conflicts.

**Review by chriss1525 — CHANGES_REQUESTED** [review]
I see you made changes to the schema.prisma, why was this necessary an was this discussed with the team lead? we need to make sure the schema stays in line with the main database and random changes might affect that. please lias with Beniah on this

**Comment by DimTony** [comment]
I've resolved the conflicts. please merge

**Review by Benrobo — CHANGES_REQUESTED** [review]
using try...catch block isn't necessary, global errors has being handled by a code, doing that would override it.

**Review by Benrobo — CHANGES_REQUESTED** [review]
this is right:
```js
if (!orderItems) {
      return this.error(res, '--orders/internal-server-error', 'Internal server Error', 500);
    }
```
INcluding how you handle the logic for returning all orders.. orders are to be matched with the merchant who was tagged when creating the order.. this whole code you wrote wont solve the problem on fetching all orders, please check the design to see what needed to be returned within the order page section and tie your code along with it.

**Review by Benrobo — CHANGES_REQUESTED** [review]
Any reason behind you commenting and deleting out code people wrote and code i wrote?

**Pull request closed without merging**
